#!/bin/bash

# Script to add Design System files to Xcode project
# This creates a list of files that need to be added

echo "Design System files to add to Xcode project:"
echo ""
echo "Tokens:"
echo "  - CurrencyConverter/DesignSystem/Tokens/OceanColors.swift"
echo "  - CurrencyConverter/DesignSystem/Tokens/OceanSpacing.swift"
echo "  - CurrencyConverter/DesignSystem/Tokens/OceanRadius.swift"
echo "  - CurrencyConverter/DesignSystem/Tokens/OceanShadows.swift"
echo "  - CurrencyConverter/DesignSystem/Tokens/OceanBlur.swift"
echo ""
echo "Extensions:"
echo "  - CurrencyConverter/DesignSystem/Extensions/Color+Ocean.swift"
echo ""
echo "View Modifiers:"
echo "  - CurrencyConverter/DesignSystem/ViewModifiers/GlassmorphismModifier.swift"
echo "  - CurrencyConverter/DesignSystem/ViewModifiers/OceanGradientModifier.swift"
echo "  - CurrencyConverter/DesignSystem/ViewModifiers/GlassCardModifier.swift"
echo "  - CurrencyConverter/DesignSystem/ViewModifiers/FloatingAnimationModifier.swift"
echo ""
echo "Components:"
echo "  - CurrencyConverter/DesignSystem/Components/OceanButton.swift"
echo "  - CurrencyConverter/DesignSystem/Components/GlassCard.swift"
echo ""
echo "To add these files to Xcode:"
echo "1. Open CurrencyConverter.xcodeproj in Xcode"
echo "2. Right-click on the CurrencyConverter group in the Project Navigator"
echo "3. Select 'Add Files to CurrencyConverter...'"
echo "4. Navigate to the DesignSystem folder"
echo "5. Select all folders (Tokens, Extensions, ViewModifiers, Components)"
echo "6. Check 'Copy items if needed' and 'Create groups'"
echo "7. Make sure the CurrencyConverter target is checked"
echo "8. Click Add"
